### ISSUE TITLE
Queries not being recorded on POST requests

### ISSUE THREAD

**Issue by zachfeldman** [scottschafer/cypressautomocker#13]
The query is blank for these for me:
{
    "method": "POST",
    "path": "<redacted>",
    "query": "",
    "request": "",
    "response": "",
    "status": 402,
    "statusText": "Payment Required",
    "contentType": "text/html; charset=utf-8"
  },
 
This is preventing the failing query case and successful query case from working correect.

**Comment by zachfeldman** [comment]
Also thanks for the great lib @scottschafer !

**Comment by scottschafer** [comment]
Sure, hope you find it useful. I'm not seeing this issue. I added an API to the example that errors with a 402 and it seems to work as expected. Perhaps try deleting your recorded mock.
