### ISSUE TITLE
Test fails when I add cypressautomocker

### ISSUE THREAD

**Issue by zachfeldman** [scottschafer/cypressautomocker#14]
Hey thanks for the lib! I was able to get it to work in 1 test. But another test passed before and is now failing. Now I get this error and it never finishes:

![image](https://user-images.githubusercontent.com/1437644/54853316-e8d43380-4cc5-11e9-81b0-c66524169903.png)

This is after adding 

```
const MOCK_FILENAME = 'bookTripSpecRecording'

  before(() => {
    cy.automock(MOCK_FILENAME);
  })

  after(() => {
    cy.automockEnd()
  })

```

The test that fails is an, "expected id of element to contain 'text' kind of assertion.

I'm not sure if it times out in my test or in waiting for automock to complete - any ideas? Thanks!

**Comment by adieCodes** [comment]
I'm having exactly the same issue having added this library. Anyone have any ideas of the issue?

**Comment by scottschafer** [comment]
If you comment out the before/after calls, does the same error occur?

Can you provide sample code that demonstrates the issue?

**Comment by adieCodes** [comment]
@scottschafer thanks for coming back to me and creating the plugin.

I've uncommented the before/after calls and the issue does not occur, leading me to believe the problem is with automocker.

For context, I have:

- Installed cypressautomocker as a dependancy
- importted and invoked `installCypressHooks` in the root component of my React app (React v16.3.2)
- Imported and invoked `registerAutoMockCommands` in commands.js
- Added the before and after blocks to my test files, the simplest example being:

```
/// <reference types="Cypress" />

describe('Login', () => {
  const username = 'testuser';
  const password = 'password`
  const MOCK_FILENAME = 'groupMock';

  before(() => {
    cy.automock(MOCK_FILENAME);
  });

  beforeEach(() => {
    cy.visit('/logout');
  });

  after(() => {
    cy.automockEnd();
  });

  it('Redirects to Dashboard after logging in', () => {
    cy.visit('/login');

    cy.get('[data-testid=username]').type(username);
    cy.get('[data-testid=password').type(password);
    cy.contains(/login/i).click();

    cy.url().should('contain', '/home');
  });

  it('Displays error if incorrect username', () => {
    cy.visit('/login');

    cy.get('[data-testid=username]').type(`${username}s`);
    cy.get('[data-testid=password]').type(password);
    cy.contains(/login/i).click();

    cy.contains('Username is invalid');
    cy.url().should('not.contain', '/home');
    cy.url().should('contain', '/login');
  });

  it('Displays error if incorrect password', () => {
    cy.visit('/login');

    cy.get('[data-testid=username]').type(username);
    cy.get('[data-testid=password').type(`${password}s`);
    cy.contains(/login/i).click();

    cy.contains('Password is incorrect');
    cy.url().should('not.contain', '/home');
    cy.url().should('contain', '/login');
  });

  it('Redirects when forgotten password clicked', () => {
    cy.visit('/login');

    cy.contains(/forgotten password/i).click();

    cy.url().should('contain', '/forgotten');
  });
});
```

Any help is greatly appreciated

**Comment by scottschafer** [comment]
The first thing I would try would be to delete the recorded mock file and allow it to be regenerated.

If that doesn't work, I'm not really sure what to tell you. I am wondering if there's an issue with visit(), and if pages are actually being reloaded in this case. That might cause issues. 

Another option would be to skip automocker for this case but possibly use it in other tests.

I wish I had a better answer and more time to look into this.
