### ISSUE TITLE
Clarification about the web hooks

### ISSUE THREAD

**Issue by dummyaccct** [scottschafer/cypressautomocker#18]
Step: "Add the cypress web hooks to your application."
Where exactly do those lines go? Into the application itself? Or somewhere in cypress. Is there any other way to do it? I am testing a web app that is already deployed to a server, so I can't change any of the application files themselves

**Comment by joenguyenalogent** [comment]
I think need to npm install the library, then import and run that registration code in your app. I think it overwrites and puts a fake xhr object in there to intercept the request/response, but I'm not sure. I'm running into issues with my Angular app w this lib at the moment.

**Comment by scottschafer** [comment]
Yeah, that's correct. I'm looking at rearchitecting this using a different technique as described here:
https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd

This wouldn't require modifying the application to be tested.

Stay tuned.
