### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by domenichelfenstein** [scottschafer/cypressautomocker#5]
Looks very promising, but I couldn't get it to work under TypeScript.
My specs as well as my commands are written in TypeScript and when I try to import the "cypressautomocker/include-in-tests" it doesn't work:

- After setting the tsconfig noImplicitAny to false it doesn't give me a compilation error no more
- But as soon as I try to run a test I get this error (inside of cypress): Uncaught TypeError: include_in_tests_1.default is not a function...

Would be great if someone has figured out how to use cypressautomocker alongside TypeScript.
Thanks in advance for all hints!

**Comment by joshmedeski** [comment]
@domenichelfenstein you have to declare the type definitions manually.

I've done this:
```ts
declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      automock: (fileName: string) => Cypress.Chainable<null>;
      automockEnd: () => Cypress.Chainable<null>;
    }
  }
}
```

I'm sure this could be done better but I'm not able to get mine working yet, I'm still troubleshooting my Angular application.

Hope it helps.

**Comment by scottschafer** [comment]
I finally have added Typescript support. Thanks for hanging in there.
