### ISSUE TITLE
Request and response objects are empty in mock files

### ISSUE THREAD

**Issue by janhoogeveen** [scottschafer/cypressautomocker#6]
**Situation:**

We've got a create-react-app where we are using the Fetch API extensively. Now we know Cypress doesn't understand the Fetch API just yet so we do the following in `support/commands.js`:

```js
beforeEach(function() {
  // If we remove window.fetch(), the polyfill will revert to XHR.
  // Cypress only supports XHR stubbing, so this is a needed evil polyfill trigger
  Cypress.on('window:before:load', win => {
    win.fetch = null;
  });
```

So far so good and this actually works while testing the app. The responses are coming in and tests pass based on those responses. However, the responses and requests are not saved in the automock files.

This is an example file of the automock we're getting:

```
[
  {
    "method": "GET",
    "path": "/api/user/preferences/something",
    "query": "",
    "request": "",
    "response": {},
    "status": 200,
    "statusText": "OK",
    "contentType": "application/json;charset=UTF-8"
  },
]
```

I'm happy to help and I'll investigate on my own as well, but any pointers on why this would break are more than welcome. We're very close to adopting Cypress in our projects, but the auto-mocking library really makes or breaks the DX for us.

**What I've already tried:**

- Removing all polyfills from the application. We are using polyfill.io to automatically polyfill a bunch of things, but even removing that completely does not help.
- Checked the network panel in the web inspector while running Cypress. API calls are coming in just fine, response data looks great.
- Checked the console, it does say it's RECORDING when I remove the mockfiles and MOCKING when I run those tests again.

**Research findings:**
In `autoMockCommands.js` on line 178 and 181, the objects are empty. The XHR object itself does contain the responses and requests, but, it is a Blob. It silently errors in the following block:

```
                try {
                  responseObject = JSON.parse(responseObject);
                  console.log({ responseObject });
                } catch (e) {
                  console.log(e);
                  debugger;
                }
```

**Comment by scottschafer** [comment]
Hi @janhoogeveen - I'm happy to take a look. Can you upload a simple application that demonstrates the issue?

**Comment by janhoogeveen** [comment]
Certainly! Thanks for the offer. 
I'll have to find some time in my schedule to get around to actually doing it, but I'll make it easy for you to look into this.

**Comment by janhoogeveen** [comment]
Hey Scott,

The easiest way to demo this problem is cloning your example repository and make the changes there. I've done that for you in a fork of your project.

https://github.com/janhoogeveen/cypressautomocker

Steps to reproduce this behavior:

1. Use `Fetch` somewhere in your API
2. Install `whatwg-fetch` polyfill  (this is included by default in create-react-app)
3. In `cypress/support/commands.js` file, remove Fetch from the global window (

Removing fetch in step 3 makes sure the Fetch polyfill is active. This polyfill uses XHR to mimick Fetch functionality and should for the most part behave similarly to jQuery's `$.ajax()` call.

There's caveats listed in the polyfills repo in how they differ from jQuery's implementation, but I'm not sure if that's related: https://github.com/github/fetch#caveats

**Comment by scottschafer** [comment]
Thanks, we're actively looking into this now.

**Comment by scottschafer** [comment]
I just pushed a fix. Please give this a try and let me know if this fixes your issue. Thanks!
